### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by bytehead** [1up-lab/contao-horizontal-rule#1]
do it!

**Comment by sheeep** [comment]
![Chuckle](http://i.imgur.com/PQX4KT0.gif)

**Comment by sheeep** [comment]
![GitHub Logo](http://i.imgur.com/soOjJCk.gif)

**Comment by bytehead** [comment]
![GitHub Logo](http://media.tumblr.com/8de556e39cd17ea086ca606dfa903fba/tumblr_inline_nhoqba6Exc1raprkq.gif)

**Comment by bytehead** [comment]
http://contao.tumblr.com/post/87982034198/writing-language-files

**Comment by sheeep** [comment]
![Meep](http://www.reactiongifs.com/r/ZuMBmk0.gif)
